# Generated by Django 4.1 on 2022-09-11 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserQuestionSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("link", models.URLField()),
                ("solved", models.BooleanField(default=False)),
                ("revised", models.BooleanField(default=False)),
                (
                    "language",
                    models.IntegerField(
                        choices=[(1, "Python"), (2, "C++"), (3, "Java"), (4, "Other")],
                        default=4,
                    ),
                ),
                ("notes", models.TextField(null=True)),
                (
                    "uid",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
