# Generated by Django 4.1 on 2022-09-11 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Array",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eqs1",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "eqr1",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "eql1",
                    models.IntegerField(
                        choices=[(1, "Python"), (2, "C++"), (3, "Java"), (4, "Other")],
                        default=4,
                    ),
                ),
                ("eqnotes1", models.TextField(blank=True, null=True)),
                (
                    "eqs2",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "eqr2",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "eql2",
                    models.IntegerField(
                        choices=[(1, "Python"), (2, "C++"), (3, "Java"), (4, "Other")],
                        default=4,
                    ),
                ),
                ("eqnotes2", models.TextField(blank=True, null=True)),
                (
                    "eqs3",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "eqr3",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "eql3",
                    models.IntegerField(
                        choices=[(1, "Python"), (2, "C++"), (3, "Java"), (4, "Other")],
                        default=4,
                    ),
                ),
                ("eqnotes3", models.TextField(blank=True, null=True)),
                (
                    "eqs4",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "eqr4",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "eql4",
                    models.IntegerField(
                        choices=[(1, "Python"), (2, "C++"), (3, "Java"), (4, "Other")],
                        default=4,
                    ),
                ),
                ("eqnotes4", models.TextField(blank=True, null=True)),
                (
                    "eqs5",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "eqr5",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "eql5",
                    models.IntegerField(
                        choices=[(1, "Python"), (2, "C++"), (3, "Java"), (4, "Other")],
                        default=4,
                    ),
                ),
                ("eqnotes5", models.TextField(blank=True, null=True)),
                (
                    "eqs6",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "eqr6",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "eql6",
                    models.IntegerField(
                        choices=[(1, "Python"), (2, "C++"), (3, "Java"), (4, "Other")],
                        default=4,
                    ),
                ),
                ("eqnotes6", models.TextField(blank=True, null=True)),
                (
                    "eqs7",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "eqr7",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "eql7",
                    models.IntegerField(
                        choices=[(1, "Python"), (2, "C++"), (3, "Java"), (4, "Other")],
                        default=4,
                    ),
                ),
                ("eqnotes7", models.TextField(blank=True, null=True)),
                (
                    "eqs8",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "eqr8",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "eql8",
                    models.IntegerField(
                        choices=[(1, "Python"), (2, "C++"), (3, "Java"), (4, "Other")],
                        default=4,
                    ),
                ),
                ("eqnotes8", models.TextField(blank=True, null=True)),
                (
                    "eqs9",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "eqr9",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "eql9",
                    models.IntegerField(
                        choices=[(1, "Python"), (2, "C++"), (3, "Java"), (4, "Other")],
                        default=4,
                    ),
                ),
                ("eqnotes9", models.TextField(blank=True, null=True)),
                (
                    "eqs10",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "eqr10",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "eql10",
                    models.IntegerField(
                        choices=[(1, "Python"), (2, "C++"), (3, "Java"), (4, "Other")],
                        default=4,
                    ),
                ),
                ("eqnotes10", models.TextField(blank=True, null=True)),
                (
                    "eqs11",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "eqr11",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "eql11",
                    models.IntegerField(
                        choices=[(1, "Python"), (2, "C++"), (3, "Java"), (4, "Other")],
                        default=4,
                    ),
                ),
                ("eqnotes11", models.TextField(blank=True, null=True)),
                (
                    "eqs12",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "eqr12",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "eql12",
                    models.IntegerField(
                        choices=[(1, "Python"), (2, "C++"), (3, "Java"), (4, "Other")],
                        default=4,
                    ),
                ),
                ("eqnotes12", models.TextField(blank=True, null=True)),
                (
                    "mqs1",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mqr1",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mql1",
                    models.IntegerField(
                        choices=[(1, "Python"), (2, "C++"), (3, "Java"), (4, "Other")],
                        default=4,
                    ),
                ),
                ("mqnotes1", models.TextField(blank=True, null=True)),
                (
                    "mqs2",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mqr2",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mql2",
                    models.IntegerField(
                        choices=[(1, "Python"), (2, "C++"), (3, "Java"), (4, "Other")],
                        default=4,
                    ),
                ),
                ("mqnotes2", models.TextField(blank=True, null=True)),
                (
                    "mqs3",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mqr3",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mql3",
                    models.IntegerField(
                        choices=[(1, "Python"), (2, "C++"), (3, "Java"), (4, "Other")],
                        default=4,
                    ),
                ),
                ("mqnotes3", models.TextField(blank=True, null=True)),
                (
                    "mqs4",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mqr4",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mql4",
                    models.IntegerField(
                        choices=[(1, "Python"), (2, "C++"), (3, "Java"), (4, "Other")],
                        default=4,
                    ),
                ),
                ("mqnotes4", models.TextField(blank=True, null=True)),
                (
                    "mqs5",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mqr5",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mql5",
                    models.IntegerField(
                        choices=[(1, "Python"), (2, "C++"), (3, "Java"), (4, "Other")],
                        default=4,
                    ),
                ),
                ("mqnotes5", models.TextField(blank=True, null=True)),
                (
                    "mqs6",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mqr6",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mql6",
                    models.IntegerField(
                        choices=[(1, "Python"), (2, "C++"), (3, "Java"), (4, "Other")],
                        default=4,
                    ),
                ),
                ("mqnotes6", models.TextField(blank=True, null=True)),
                (
                    "mqs7",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mqr7",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mql7",
                    models.IntegerField(
                        choices=[(1, "Python"), (2, "C++"), (3, "Java"), (4, "Other")],
                        default=4,
                    ),
                ),
                ("mqnotes7", models.TextField(blank=True, null=True)),
                (
                    "mqs8",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mqr8",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mql8",
                    models.IntegerField(
                        choices=[(1, "Python"), (2, "C++"), (3, "Java"), (4, "Other")],
                        default=4,
                    ),
                ),
                ("mqnotes8", models.TextField(blank=True, null=True)),
                (
                    "mqs9",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mqr9",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mql9",
                    models.IntegerField(
                        choices=[(1, "Python"), (2, "C++"), (3, "Java"), (4, "Other")],
                        default=4,
                    ),
                ),
                ("mqnotes9", models.TextField(blank=True, null=True)),
                (
                    "mqs10",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mqr10",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mql10",
                    models.IntegerField(
                        choices=[(1, "Python"), (2, "C++"), (3, "Java"), (4, "Other")],
                        default=4,
                    ),
                ),
                ("mqnotes10", models.TextField(blank=True, null=True)),
                (
                    "mqs11",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mqr11",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mql11",
                    models.IntegerField(
                        choices=[(1, "Python"), (2, "C++"), (3, "Java"), (4, "Other")],
                        default=4,
                    ),
                ),
                ("mqnotes11", models.TextField(blank=True, null=True)),
                (
                    "mqs12",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mqr12",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mql12",
                    models.IntegerField(
                        choices=[(1, "Python"), (2, "C++"), (3, "Java"), (4, "Other")],
                        default=4,
                    ),
                ),
                ("mqnotes12", models.TextField(blank=True, null=True)),
                (
                    "mqs13",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mqr13",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mql13",
                    models.IntegerField(
                        choices=[(1, "Python"), (2, "C++"), (3, "Java"), (4, "Other")],
                        default=4,
                    ),
                ),
                ("mqnotes13", models.TextField(blank=True, null=True)),
                (
                    "mqs14",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mqr14",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mql14",
                    models.IntegerField(
                        choices=[(1, "Python"), (2, "C++"), (3, "Java"), (4, "Other")],
                        default=4,
                    ),
                ),
                ("mqnotes14", models.TextField(blank=True, null=True)),
                (
                    "mqs15",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mqr15",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mql15",
                    models.IntegerField(
                        choices=[(1, "Python"), (2, "C++"), (3, "Java"), (4, "Other")],
                        default=4,
                    ),
                ),
                ("mqnotes15", models.TextField(blank=True, null=True)),
                (
                    "mqs16",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mqr16",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mql16",
                    models.IntegerField(
                        choices=[(1, "Python"), (2, "C++"), (3, "Java"), (4, "Other")],
                        default=4,
                    ),
                ),
                ("mqnotes16", models.TextField(blank=True, null=True)),
                (
                    "mqs17",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mqr17",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mql17",
                    models.IntegerField(
                        choices=[(1, "Python"), (2, "C++"), (3, "Java"), (4, "Other")],
                        default=4,
                    ),
                ),
                ("mqnotes17", models.TextField(blank=True, null=True)),
                (
                    "mqs18",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mqr18",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mql18",
                    models.IntegerField(
                        choices=[(1, "Python"), (2, "C++"), (3, "Java"), (4, "Other")],
                        default=4,
                    ),
                ),
                ("mqnotes18", models.TextField(blank=True, null=True)),
                (
                    "mqs19",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mqr19",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mql19",
                    models.IntegerField(
                        choices=[(1, "Python"), (2, "C++"), (3, "Java"), (4, "Other")],
                        default=4,
                    ),
                ),
                ("mqnotes19", models.TextField(blank=True, null=True)),
                (
                    "mqs20",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mqr20",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mql20",
                    models.IntegerField(
                        choices=[(1, "Python"), (2, "C++"), (3, "Java"), (4, "Other")],
                        default=4,
                    ),
                ),
                ("mqnotes20", models.TextField(blank=True, null=True)),
                (
                    "mqs21",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mqr21",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mql21",
                    models.IntegerField(
                        choices=[(1, "Python"), (2, "C++"), (3, "Java"), (4, "Other")],
                        default=4,
                    ),
                ),
                ("mqnotes21", models.TextField(blank=True, null=True)),
                (
                    "mqs22",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mqr22",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mql22",
                    models.IntegerField(
                        choices=[(1, "Python"), (2, "C++"), (3, "Java"), (4, "Other")],
                        default=4,
                    ),
                ),
                ("mqnotes22", models.TextField(blank=True, null=True)),
                (
                    "mqs23",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mqr23",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mql23",
                    models.IntegerField(
                        choices=[(1, "Python"), (2, "C++"), (3, "Java"), (4, "Other")],
                        default=4,
                    ),
                ),
                ("mqnotes23", models.TextField(blank=True, null=True)),
                (
                    "mqs24",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mqr24",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mql24",
                    models.IntegerField(
                        choices=[(1, "Python"), (2, "C++"), (3, "Java"), (4, "Other")],
                        default=4,
                    ),
                ),
                ("mqnotes24", models.TextField(blank=True, null=True)),
                (
                    "mqs25",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mqr25",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mql25",
                    models.IntegerField(
                        choices=[(1, "Python"), (2, "C++"), (3, "Java"), (4, "Other")],
                        default=4,
                    ),
                ),
                ("mqnotes25", models.TextField(blank=True, null=True)),
                (
                    "mqs26",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mqr26",
                    models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
                ),
                (
                    "mql26",
                    models.IntegerField(
                        choices=[(1, "Python"), (2, "C++"), (3, "Java"), (4, "Other")],
                        default=4,
                    ),
                ),
                ("mqnotes26", models.TextField(blank=True, null=True)),
                (
                    "uid",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
