# Generated by Django 4.1 on 2022-09-11 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dsasheet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="array",
            name="hql1",
            field=models.IntegerField(
                choices=[(1, "Python"), (2, "C++"), (3, "Java"), (4, "Other")],
                default=4,
            ),
        ),
        migrations.AddField(
            model_name="array",
            name="hql2",
            field=models.IntegerField(
                choices=[(1, "Python"), (2, "C++"), (3, "Java"), (4, "Other")],
                default=4,
            ),
        ),
        migrations.AddField(
            model_name="array",
            name="hql3",
            field=models.IntegerField(
                choices=[(1, "Python"), (2, "C++"), (3, "Java"), (4, "Other")],
                default=4,
            ),
        ),
        migrations.AddField(
            model_name="array",
            name="hql4",
            field=models.IntegerField(
                choices=[(1, "Python"), (2, "C++"), (3, "Java"), (4, "Other")],
                default=4,
            ),
        ),
        migrations.AddField(
            model_name="array",
            name="hql5",
            field=models.IntegerField(
                choices=[(1, "Python"), (2, "C++"), (3, "Java"), (4, "Other")],
                default=4,
            ),
        ),
        migrations.AddField(
            model_name="array",
            name="hqnotes1",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="array",
            name="hqnotes2",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="array",
            name="hqnotes3",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="array",
            name="hqnotes4",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="array",
            name="hqnotes5",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="array",
            name="hqr1",
            field=models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
        ),
        migrations.AddField(
            model_name="array",
            name="hqr2",
            field=models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
        ),
        migrations.AddField(
            model_name="array",
            name="hqr3",
            field=models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
        ),
        migrations.AddField(
            model_name="array",
            name="hqr4",
            field=models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
        ),
        migrations.AddField(
            model_name="array",
            name="hqr5",
            field=models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
        ),
        migrations.AddField(
            model_name="array",
            name="hqs1",
            field=models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
        ),
        migrations.AddField(
            model_name="array",
            name="hqs2",
            field=models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
        ),
        migrations.AddField(
            model_name="array",
            name="hqs3",
            field=models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
        ),
        migrations.AddField(
            model_name="array",
            name="hqs4",
            field=models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
        ),
        migrations.AddField(
            model_name="array",
            name="hqs5",
            field=models.IntegerField(choices=[(1, "Yes"), (2, "No")], default=2),
        ),
    ]
