from django.db import models
from django.contrib.auth.models import User


class DynamicP(models.Model):
    uid = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    lang = [(1, 'Python'), (2, 'C++'), (3, 'Java'), (4, 'Other')]
    yn = [(1, 'Yes'), (2, 'No')]

    eqs1 = models.IntegerField(choices=yn, default=2)
    eqr1 = models.IntegerField(choices=yn, default=2)
    eql1 = models.IntegerField(choices=lang, default=4)
    eqnotes1 = models.TextField(null=True, blank=True)
    eqs2 = models.IntegerField(choices=yn, default=2)
    eqr2 = models.IntegerField(choices=yn, default=2)
    eql2 = models.IntegerField(choices=lang, default=4)
    eqnotes2 = models.TextField(null=True, blank=True)
    eqs3 = models.IntegerField(choices=yn, default=2)
    eqr3 = models.IntegerField(choices=yn, default=2)
    eql3 = models.IntegerField(choices=lang, default=4)
    eqnotes3 = models.TextField(null=True, blank=True)
    eqs4 = models.IntegerField(choices=yn, default=2)
    eqr4 = models.IntegerField(choices=yn, default=2)
    eql4 = models.IntegerField(choices=lang, default=4)
    eqnotes4 = models.TextField(null=True, blank=True)

    mqs1 = models.IntegerField(choices=yn, default=2)
    mqr1 = models.IntegerField(choices=yn, default=2)
    mql1 = models.IntegerField(choices=lang, default=4)
    mqnotes1 = models.TextField(null=True, blank=True)
    mqs2 = models.IntegerField(choices=yn, default=2)
    mqr2 = models.IntegerField(choices=yn, default=2)
    mql2 = models.IntegerField(choices=lang, default=4)
    mqnotes2 = models.TextField(null=True, blank=True)
    mqs3 = models.IntegerField(choices=yn, default=2)
    mqr3 = models.IntegerField(choices=yn, default=2)
    mql3 = models.IntegerField(choices=lang, default=4)
    mqnotes3 = models.TextField(null=True, blank=True)
    mqs4 = models.IntegerField(choices=yn, default=2)
    mqr4 = models.IntegerField(choices=yn, default=2)
    mql4 = models.IntegerField(choices=lang, default=4)
    mqnotes4 = models.TextField(null=True, blank=True)
    mqs5 = models.IntegerField(choices=yn, default=2)
    mqr5 = models.IntegerField(choices=yn, default=2)
    mql5 = models.IntegerField(choices=lang, default=4)
    mqnotes5 = models.TextField(null=True, blank=True)
    mqs6 = models.IntegerField(choices=yn, default=2)
    mqr6 = models.IntegerField(choices=yn, default=2)
    mql6 = models.IntegerField(choices=lang, default=4)
    mqnotes6 = models.TextField(null=True, blank=True)
    mqs7 = models.IntegerField(choices=yn, default=2)
    mqr7 = models.IntegerField(choices=yn, default=2)
    mql7 = models.IntegerField(choices=lang, default=4)
    mqnotes7 = models.TextField(null=True, blank=True)
    mqs8 = models.IntegerField(choices=yn, default=2)
    mqr8 = models.IntegerField(choices=yn, default=2)
    mql8 = models.IntegerField(choices=lang, default=4)
    mqnotes8 = models.TextField(null=True, blank=True)
    mqs9 = models.IntegerField(choices=yn, default=2)
    mqr9 = models.IntegerField(choices=yn, default=2)
    mql9 = models.IntegerField(choices=lang, default=4)
    mqnotes9 = models.TextField(null=True, blank=True)
    mqs10 = models.IntegerField(choices=yn, default=2)
    mqr10 = models.IntegerField(choices=yn, default=2)
    mql10 = models.IntegerField(choices=lang, default=4)
    mqnotes10 = models.TextField(null=True, blank=True)
    mqs11 = models.IntegerField(choices=yn, default=2)
    mqr11 = models.IntegerField(choices=yn, default=2)
    mql11 = models.IntegerField(choices=lang, default=4)
    mqnotes11 = models.TextField(null=True, blank=True)
    mqs12 = models.IntegerField(choices=yn, default=2)
    mqr12 = models.IntegerField(choices=yn, default=2)
    mql12 = models.IntegerField(choices=lang, default=4)
    mqnotes12 = models.TextField(null=True, blank=True)
    mqs13 = models.IntegerField(choices=yn, default=2)
    mqr13 = models.IntegerField(choices=yn, default=2)
    mql13 = models.IntegerField(choices=lang, default=4)
    mqnotes13 = models.TextField(null=True, blank=True)
    mqs14 = models.IntegerField(choices=yn, default=2)
    mqr14 = models.IntegerField(choices=yn, default=2)
    mql14 = models.IntegerField(choices=lang, default=4)
    mqnotes14 = models.TextField(null=True, blank=True)
    mqs15 = models.IntegerField(choices=yn, default=2)
    mqr15 = models.IntegerField(choices=yn, default=2)
    mql15 = models.IntegerField(choices=lang, default=4)
    mqnotes15 = models.TextField(null=True, blank=True)
    mqs16 = models.IntegerField(choices=yn, default=2)
    mqr16 = models.IntegerField(choices=yn, default=2)
    mql16 = models.IntegerField(choices=lang, default=4)
    mqnotes16 = models.TextField(null=True, blank=True)

    hqs1 = models.IntegerField(choices=yn, default=2)
    hqr1 = models.IntegerField(choices=yn, default=2)
    hql1 = models.IntegerField(choices=lang, default=4)
    hqnotes1 = models.TextField(null=True, blank=True)
    hqs2 = models.IntegerField(choices=yn, default=2)
    hqr2 = models.IntegerField(choices=yn, default=2)
    hql2 = models.IntegerField(choices=lang, default=4)
    hqnotes2 = models.TextField(null=True, blank=True)
    hqs3 = models.IntegerField(choices=yn, default=2)
    hqr3 = models.IntegerField(choices=yn, default=2)
    hql3 = models.IntegerField(choices=lang, default=4)
    hqnotes3 = models.TextField(null=True, blank=True)
    hqs4 = models.IntegerField(choices=yn, default=2)
    hqr4 = models.IntegerField(choices=yn, default=2)
    hql4 = models.IntegerField(choices=lang, default=4)
    hqnotes4 = models.TextField(null=True, blank=True)
    hqs5 = models.IntegerField(choices=yn, default=2)
    hqr5 = models.IntegerField(choices=yn, default=2)
    hql5 = models.IntegerField(choices=lang, default=4)
    hqnotes5 = models.TextField(null=True, blank=True)
    hqs6 = models.IntegerField(choices=yn, default=2)
    hqr6 = models.IntegerField(choices=yn, default=2)
    hql6 = models.IntegerField(choices=lang, default=4)
    hqnotes6 = models.TextField(null=True, blank=True)
    hqs7 = models.IntegerField(choices=yn, default=2)
    hqr7 = models.IntegerField(choices=yn, default=2)
    hql7 = models.IntegerField(choices=lang, default=4)
    hqnotes7 = models.TextField(null=True, blank=True)
    hqs8 = models.IntegerField(choices=yn, default=2)
    hqr8 = models.IntegerField(choices=yn, default=2)
    hql8 = models.IntegerField(choices=lang, default=4)
    hqnotes8 = models.TextField(null=True, blank=True)
    hqs9 = models.IntegerField(choices=yn, default=2)
    hqr9 = models.IntegerField(choices=yn, default=2)
    hql9 = models.IntegerField(choices=lang, default=4)
    hqnotes9 = models.TextField(null=True, blank=True)
    hqs10 = models.IntegerField(choices=yn, default=2)
    hqr10 = models.IntegerField(choices=yn, default=2)
    hql10 = models.IntegerField(choices=lang, default=4)
    hqnotes10 = models.TextField(null=True, blank=True)
    hqs11 = models.IntegerField(choices=yn, default=2)
    hqr11 = models.IntegerField(choices=yn, default=2)
    hql11 = models.IntegerField(choices=lang, default=4)
    hqnotes11 = models.TextField(null=True, blank=True)
    hqs12 = models.IntegerField(choices=yn, default=2)
    hqr12 = models.IntegerField(choices=yn, default=2)
    hql12 = models.IntegerField(choices=lang, default=4)
    hqnotes12 = models.TextField(null=True, blank=True)
    hqs13 = models.IntegerField(choices=yn, default=2)
    hqr13 = models.IntegerField(choices=yn, default=2)
    hql13 = models.IntegerField(choices=lang, default=4)
    hqnotes13 = models.TextField(null=True, blank=True)
    hqs14 = models.IntegerField(choices=yn, default=2)
    hqr14 = models.IntegerField(choices=yn, default=2)
    hql14 = models.IntegerField(choices=lang, default=4)
    hqnotes14 = models.TextField(null=True, blank=True)
    hqs15 = models.IntegerField(choices=yn, default=2)
    hqr15 = models.IntegerField(choices=yn, default=2)
    hql15 = models.IntegerField(choices=lang, default=4)
    hqnotes15 = models.TextField(null=True, blank=True)

    def __str__(self):
        return str(self.uid)

    def __getitem__(self, key):
        return getattr(self, key)
