from django.db import models
from django.contrib.auth.models import User


class Graph(models.Model):
    uid = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    lang = [(1, 'Python'), (2, 'C++'), (3, 'Java'), (4, 'Other')]
    yn = [(1, 'Yes'), (2, 'No')]

    eqs1 = models.IntegerField(choices=yn, default=2)
    eqr1 = models.IntegerField(choices=yn, default=2)
    eql1 = models.IntegerField(choices=lang, default=4)
    eqnotes1 = models.TextField(null=True, blank=True)
    eqs2 = models.IntegerField(choices=yn, default=2)
    eqr2 = models.IntegerField(choices=yn, default=2)
    eql2 = models.IntegerField(choices=lang, default=4)
    eqnotes2 = models.TextField(null=True, blank=True)

    mqs1 = models.IntegerField(choices=yn, default=2)
    mqr1 = models.IntegerField(choices=yn, default=2)
    mql1 = models.IntegerField(choices=lang, default=4)
    mqnotes1 = models.TextField(null=True, blank=True)
    mqs2 = models.IntegerField(choices=yn, default=2)
    mqr2 = models.IntegerField(choices=yn, default=2)
    mql2 = models.IntegerField(choices=lang, default=4)
    mqnotes2 = models.TextField(null=True, blank=True)
    mqs3 = models.IntegerField(choices=yn, default=2)
    mqr3 = models.IntegerField(choices=yn, default=2)
    mql3 = models.IntegerField(choices=lang, default=4)
    mqnotes3 = models.TextField(null=True, blank=True)
    mqs4 = models.IntegerField(choices=yn, default=2)
    mqr4 = models.IntegerField(choices=yn, default=2)
    mql4 = models.IntegerField(choices=lang, default=4)
    mqnotes4 = models.TextField(null=True, blank=True)
    mqs5 = models.IntegerField(choices=yn, default=2)
    mqr5 = models.IntegerField(choices=yn, default=2)
    mql5 = models.IntegerField(choices=lang, default=4)
    mqnotes5 = models.TextField(null=True, blank=True)
    mqs6 = models.IntegerField(choices=yn, default=2)
    mqr6 = models.IntegerField(choices=yn, default=2)
    mql6 = models.IntegerField(choices=lang, default=4)
    mqnotes6 = models.TextField(null=True, blank=True)
    mqs7 = models.IntegerField(choices=yn, default=2)
    mqr7 = models.IntegerField(choices=yn, default=2)
    mql7 = models.IntegerField(choices=lang, default=4)
    mqnotes7 = models.TextField(null=True, blank=True)
    mqs8 = models.IntegerField(choices=yn, default=2)
    mqr8 = models.IntegerField(choices=yn, default=2)
    mql8 = models.IntegerField(choices=lang, default=4)
    mqnotes8 = models.TextField(null=True, blank=True)
    mqs9 = models.IntegerField(choices=yn, default=2)
    mqr9 = models.IntegerField(choices=yn, default=2)
    mql9 = models.IntegerField(choices=lang, default=4)
    mqnotes9 = models.TextField(null=True, blank=True)
    mqs10 = models.IntegerField(choices=yn, default=2)
    mqr10 = models.IntegerField(choices=yn, default=2)
    mql10 = models.IntegerField(choices=lang, default=4)
    mqnotes10 = models.TextField(null=True, blank=True)
    mqs11 = models.IntegerField(choices=yn, default=2)
    mqr11 = models.IntegerField(choices=yn, default=2)
    mql11 = models.IntegerField(choices=lang, default=4)
    mqnotes11 = models.TextField(null=True, blank=True)
    mqs12 = models.IntegerField(choices=yn, default=2)
    mqr12 = models.IntegerField(choices=yn, default=2)
    mql12 = models.IntegerField(choices=lang, default=4)
    mqnotes12 = models.TextField(null=True, blank=True)
    mqs13 = models.IntegerField(choices=yn, default=2)
    mqr13 = models.IntegerField(choices=yn, default=2)
    mql13 = models.IntegerField(choices=lang, default=4)
    mqnotes13 = models.TextField(null=True, blank=True)
    mqs14 = models.IntegerField(choices=yn, default=2)
    mqr14 = models.IntegerField(choices=yn, default=2)
    mql14 = models.IntegerField(choices=lang, default=4)
    mqnotes14 = models.TextField(null=True, blank=True)

    def __str__(self):
        return str(self.uid)

    def __getitem__(self, key):
        return getattr(self, key)
