from django.db import models
from django.contrib.auth.models import User


# Hash Map and Binary Search
class Hash(models.Model):
    uid = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    lang = [(1, 'Python'), (2, 'C++'), (3, 'Java'), (4, 'Other')]
    yn = [(1, 'Yes'), (2, 'No')]

    heqs1 = models.IntegerField(choices=yn, default=2)
    heqr1 = models.IntegerField(choices=yn, default=2)
    heql1 = models.IntegerField(choices=lang, default=4)
    heqnotes1 = models.TextField(null=True, blank=True)
    heqs2 = models.IntegerField(choices=yn, default=2)
    heqr2 = models.IntegerField(choices=yn, default=2)
    heql2 = models.IntegerField(choices=lang, default=4)
    heqnotes2 = models.TextField(null=True, blank=True)

    hmqs1 = models.IntegerField(choices=yn, default=2)
    hmqr1 = models.IntegerField(choices=yn, default=2)
    hmql1 = models.IntegerField(choices=lang, default=4)
    hmqnotes1 = models.TextField(null=True, blank=True)
    hmqs2 = models.IntegerField(choices=yn, default=2)
    hmqr2 = models.IntegerField(choices=yn, default=2)
    hmql2 = models.IntegerField(choices=lang, default=4)
    hmqnotes2 = models.TextField(null=True, blank=True)

    beqs1 = models.IntegerField(choices=yn, default=2)
    beqr1 = models.IntegerField(choices=yn, default=2)
    beql1 = models.IntegerField(choices=lang, default=4)
    beqnotes1 = models.TextField(null=True, blank=True)
    beqs2 = models.IntegerField(choices=yn, default=2)
    beqr2 = models.IntegerField(choices=yn, default=2)
    beql2 = models.IntegerField(choices=lang, default=4)
    beqnotes2 = models.TextField(null=True, blank=True)
    beqs3 = models.IntegerField(choices=yn, default=2)
    beqr3 = models.IntegerField(choices=yn, default=2)
    beql3 = models.IntegerField(choices=lang, default=4)
    beqnotes3 = models.TextField(null=True, blank=True)
    beqs4 = models.IntegerField(choices=yn, default=2)
    beqr4 = models.IntegerField(choices=yn, default=2)
    beql4 = models.IntegerField(choices=lang, default=4)
    beqnotes4 = models.TextField(null=True, blank=True)

    bmqs1 = models.IntegerField(choices=yn, default=2)
    bmqr1 = models.IntegerField(choices=yn, default=2)
    bmql1 = models.IntegerField(choices=lang, default=4)
    bmqnotes1 = models.TextField(null=True, blank=True)
    bmqs2 = models.IntegerField(choices=yn, default=2)
    bmqr2 = models.IntegerField(choices=yn, default=2)
    bmql2 = models.IntegerField(choices=lang, default=4)
    bmqnotes2 = models.TextField(null=True, blank=True)
    bmqs3 = models.IntegerField(choices=yn, default=2)
    bmqr3 = models.IntegerField(choices=yn, default=2)
    bmql3 = models.IntegerField(choices=lang, default=4)
    bmqnotes3 = models.TextField(null=True, blank=True)
    bmqs4 = models.IntegerField(choices=yn, default=2)
    bmqr4 = models.IntegerField(choices=yn, default=2)
    bmql4 = models.IntegerField(choices=lang, default=4)
    bmqnotes4 = models.TextField(null=True, blank=True)
    bmqs5 = models.IntegerField(choices=yn, default=2)
    bmqr5 = models.IntegerField(choices=yn, default=2)
    bmql5 = models.IntegerField(choices=lang, default=4)
    bmqnotes5 = models.TextField(null=True, blank=True)
    bmqs6 = models.IntegerField(choices=yn, default=2)
    bmqr6 = models.IntegerField(choices=yn, default=2)
    bmql6 = models.IntegerField(choices=lang, default=4)
    bmqnotes6 = models.TextField(null=True, blank=True)
    bmqs7 = models.IntegerField(choices=yn, default=2)
    bmqr7 = models.IntegerField(choices=yn, default=2)
    bmql7 = models.IntegerField(choices=lang, default=4)
    bmqnotes7 = models.TextField(null=True, blank=True)
    bmqs8 = models.IntegerField(choices=yn, default=2)
    bmqr8 = models.IntegerField(choices=yn, default=2)
    bmql8 = models.IntegerField(choices=lang, default=4)
    bmqnotes8 = models.TextField(null=True, blank=True)
    bmqs9 = models.IntegerField(choices=yn, default=2)
    bmqr9 = models.IntegerField(choices=yn, default=2)
    bmql9 = models.IntegerField(choices=lang, default=4)
    bmqnotes9 = models.TextField(null=True, blank=True)

    bhqs1 = models.IntegerField(choices=yn, default=2)
    bhqr1 = models.IntegerField(choices=yn, default=2)
    bhql1 = models.IntegerField(choices=lang, default=4)
    bhqnotes1 = models.TextField(null=True, blank=True)
    bhqs2 = models.IntegerField(choices=yn, default=2)
    bhqr2 = models.IntegerField(choices=yn, default=2)
    bhql2 = models.IntegerField(choices=lang, default=4)
    bhqnotes2 = models.TextField(null=True, blank=True)
    bhqs3 = models.IntegerField(choices=yn, default=2)
    bhqr3 = models.IntegerField(choices=yn, default=2)
    bhql3 = models.IntegerField(choices=lang, default=4)
    bhqnotes3 = models.TextField(null=True, blank=True)
    bhqs4 = models.IntegerField(choices=yn, default=2)
    bhqr4 = models.IntegerField(choices=yn, default=2)
    bhql4 = models.IntegerField(choices=lang, default=4)
    bhqnotes4 = models.TextField(null=True, blank=True)
    bhqs5 = models.IntegerField(choices=yn, default=2)
    bhqr5 = models.IntegerField(choices=yn, default=2)
    bhql5 = models.IntegerField(choices=lang, default=4)
    bhqnotes5 = models.TextField(null=True, blank=True)

    def __str__(self):
        return str(self.uid)

    def __getitem__(self, key):
        return getattr(self, key)
