from django.db import models
from django.contrib.auth.models import User


# Math and Greedy
class Maths(models.Model):
    uid = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    lang = [(1, 'Python'), (2, 'C++'), (3, 'Java'), (4, 'Other')]
    yn = [(1, 'Yes'), (2, 'No')]

    meqs1 = models.IntegerField(choices=yn, default=2)
    meqr1 = models.IntegerField(choices=yn, default=2)
    meql1 = models.IntegerField(choices=lang, default=4)
    meqnotes1 = models.TextField(null=True, blank=True)
    meqs2 = models.IntegerField(choices=yn, default=2)
    meqr2 = models.IntegerField(choices=yn, default=2)
    meql2 = models.IntegerField(choices=lang, default=4)
    meqnotes2 = models.TextField(null=True, blank=True)
    meqs3 = models.IntegerField(choices=yn, default=2)
    meqr3 = models.IntegerField(choices=yn, default=2)
    meql3 = models.IntegerField(choices=lang, default=4)
    meqnotes3 = models.TextField(null=True, blank=True)
    meqs4 = models.IntegerField(choices=yn, default=2)
    meqr4 = models.IntegerField(choices=yn, default=2)
    meql4 = models.IntegerField(choices=lang, default=4)
    meqnotes4 = models.TextField(null=True, blank=True)
    meqs5 = models.IntegerField(choices=yn, default=2)
    meqr5 = models.IntegerField(choices=yn, default=2)
    meql5 = models.IntegerField(choices=lang, default=4)
    meqnotes5 = models.TextField(null=True, blank=True)
    meqs6 = models.IntegerField(choices=yn, default=2)
    meqr6 = models.IntegerField(choices=yn, default=2)
    meql6 = models.IntegerField(choices=lang, default=4)
    meqnotes6 = models.TextField(null=True, blank=True)
    meqs7 = models.IntegerField(choices=yn, default=2)
    meqr7 = models.IntegerField(choices=yn, default=2)
    meql7 = models.IntegerField(choices=lang, default=4)
    meqnotes7 = models.TextField(null=True, blank=True)
    meqs8 = models.IntegerField(choices=yn, default=2)
    meqr8 = models.IntegerField(choices=yn, default=2)
    meql8 = models.IntegerField(choices=lang, default=4)
    meqnotes8 = models.TextField(null=True, blank=True)
    meqs9 = models.IntegerField(choices=yn, default=2)
    meqr9 = models.IntegerField(choices=yn, default=2)
    meql9 = models.IntegerField(choices=lang, default=4)
    meqnotes9 = models.TextField(null=True, blank=True)

    mmqs1 = models.IntegerField(choices=yn, default=2)
    mmqr1 = models.IntegerField(choices=yn, default=2)
    mmql1 = models.IntegerField(choices=lang, default=4)
    mmqnotes1 = models.TextField(null=True, blank=True)
    mmqs2 = models.IntegerField(choices=yn, default=2)
    mmqr2 = models.IntegerField(choices=yn, default=2)
    mmql2 = models.IntegerField(choices=lang, default=4)
    mmqnotes2 = models.TextField(null=True, blank=True)
    mmqs3 = models.IntegerField(choices=yn, default=2)
    mmqr3 = models.IntegerField(choices=yn, default=2)
    mmql3 = models.IntegerField(choices=lang, default=4)
    mmqnotes3 = models.TextField(null=True, blank=True)
    mmqs4 = models.IntegerField(choices=yn, default=2)
    mmqr4 = models.IntegerField(choices=yn, default=2)
    mmql4 = models.IntegerField(choices=lang, default=4)
    mmqnotes4 = models.TextField(null=True, blank=True)
    mmqs5 = models.IntegerField(choices=yn, default=2)
    mmqr5 = models.IntegerField(choices=yn, default=2)
    mmql5 = models.IntegerField(choices=lang, default=4)
    mmqnotes5 = models.TextField(null=True, blank=True)
    mmqs6 = models.IntegerField(choices=yn, default=2)
    mmqr6 = models.IntegerField(choices=yn, default=2)
    mmql6 = models.IntegerField(choices=lang, default=4)
    mmqnotes6 = models.TextField(null=True, blank=True)
    mmqs7 = models.IntegerField(choices=yn, default=2)
    mmqr7 = models.IntegerField(choices=yn, default=2)
    mmql7 = models.IntegerField(choices=lang, default=4)
    mmqnotes7 = models.TextField(null=True, blank=True)

    mhqs1 = models.IntegerField(choices=yn, default=2)
    mhqr1 = models.IntegerField(choices=yn, default=2)
    mhql1 = models.IntegerField(choices=lang, default=4)
    mhqnotes1 = models.TextField(null=True, blank=True)
    mhqs2 = models.IntegerField(choices=yn, default=2)
    mhqr2 = models.IntegerField(choices=yn, default=2)
    mhql2 = models.IntegerField(choices=lang, default=4)
    mhqnotes2 = models.TextField(null=True, blank=True)
    mhqs3 = models.IntegerField(choices=yn, default=2)
    mhqr3 = models.IntegerField(choices=yn, default=2)
    mhql3 = models.IntegerField(choices=lang, default=4)
    mhqnotes3 = models.TextField(null=True, blank=True)
    mhqs4 = models.IntegerField(choices=yn, default=2)
    mhqr4 = models.IntegerField(choices=yn, default=2)
    mhql4 = models.IntegerField(choices=lang, default=4)
    mhqnotes4 = models.TextField(null=True, blank=True)

    gmqs1 = models.IntegerField(choices=yn, default=2)
    gmqr1 = models.IntegerField(choices=yn, default=2)
    gmql1 = models.IntegerField(choices=lang, default=4)
    gmqnotes1 = models.TextField(null=True, blank=True)
    gmqs2 = models.IntegerField(choices=yn, default=2)
    gmqr2 = models.IntegerField(choices=yn, default=2)
    gmql2 = models.IntegerField(choices=lang, default=4)
    gmqnotes2 = models.TextField(null=True, blank=True)
    gmqs3 = models.IntegerField(choices=yn, default=2)
    gmqr3 = models.IntegerField(choices=yn, default=2)
    gmql3 = models.IntegerField(choices=lang, default=4)
    gmqnotes3 = models.TextField(null=True, blank=True)
    gmqs4 = models.IntegerField(choices=yn, default=2)
    gmqr4 = models.IntegerField(choices=yn, default=2)
    gmql4 = models.IntegerField(choices=lang, default=4)
    gmqnotes4 = models.TextField(null=True, blank=True)
    gmqs5 = models.IntegerField(choices=yn, default=2)
    gmqr5 = models.IntegerField(choices=yn, default=2)
    gmql5 = models.IntegerField(choices=lang, default=4)
    gmqnotes5 = models.TextField(null=True, blank=True)
    gmqs6 = models.IntegerField(choices=yn, default=2)
    gmqr6 = models.IntegerField(choices=yn, default=2)
    gmql6 = models.IntegerField(choices=lang, default=4)
    gmqnotes6 = models.TextField(null=True, blank=True)
    gmqs7 = models.IntegerField(choices=yn, default=2)
    gmqr7 = models.IntegerField(choices=yn, default=2)
    gmql7 = models.IntegerField(choices=lang, default=4)
    gmqnotes7 = models.TextField(null=True, blank=True)
    gmqs8 = models.IntegerField(choices=yn, default=2)
    gmqr8 = models.IntegerField(choices=yn, default=2)
    gmql8 = models.IntegerField(choices=lang, default=4)
    gmqnotes8 = models.TextField(null=True, blank=True)

    ghqs1 = models.IntegerField(choices=yn, default=2)
    ghqr1 = models.IntegerField(choices=yn, default=2)
    ghql1 = models.IntegerField(choices=lang, default=4)
    ghqnotes1 = models.TextField(null=True, blank=True)
    ghqs2 = models.IntegerField(choices=yn, default=2)
    ghqr2 = models.IntegerField(choices=yn, default=2)
    ghql2 = models.IntegerField(choices=lang, default=4)
    ghqnotes2 = models.TextField(null=True, blank=True)
    ghqs3 = models.IntegerField(choices=yn, default=2)
    ghqr3 = models.IntegerField(choices=yn, default=2)
    ghql3 = models.IntegerField(choices=lang, default=4)
    ghqnotes3 = models.TextField(null=True, blank=True)

    def __str__(self):
        return str(self.uid)

    def __getitem__(self, key):
        return getattr(self, key)
