from django.db import models
from django.contrib.auth.models import User


# Two Pointer, Sliding Window and Stack
class Stack(models.Model):
    uid = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    lang = [(1, 'Python'), (2, 'C++'), (3, 'Java'), (4, 'Other')]
    yn = [(1, 'Yes'), (2, 'No')]

    tqs1 = models.IntegerField(choices=yn, default=2)
    tqr1 = models.IntegerField(choices=yn, default=2)
    tql1 = models.IntegerField(choices=lang, default=4)
    tqnotes1 = models.TextField(null=True, blank=True)
    tqs2 = models.IntegerField(choices=yn, default=2)
    tqr2 = models.IntegerField(choices=yn, default=2)
    tql2 = models.IntegerField(choices=lang, default=4)
    tqnotes2 = models.TextField(null=True, blank=True)
    tqs3 = models.IntegerField(choices=yn, default=2)
    tqr3 = models.IntegerField(choices=yn, default=2)
    tql3 = models.IntegerField(choices=lang, default=4)
    tqnotes3 = models.TextField(null=True, blank=True)
    tqs4 = models.IntegerField(choices=yn, default=2)
    tqr4 = models.IntegerField(choices=yn, default=2)
    tql4 = models.IntegerField(choices=lang, default=4)
    tqnotes4 = models.TextField(null=True, blank=True)
    tqs5 = models.IntegerField(choices=yn, default=2)
    tqr5 = models.IntegerField(choices=yn, default=2)
    tql5 = models.IntegerField(choices=lang, default=4)
    tqnotes5 = models.TextField(null=True, blank=True)

    swqs1 = models.IntegerField(choices=yn, default=2)
    swqr1 = models.IntegerField(choices=yn, default=2)
    swql1 = models.IntegerField(choices=lang, default=4)
    swqnotes1 = models.TextField(null=True, blank=True)
    swqs2 = models.IntegerField(choices=yn, default=2)
    swqr2 = models.IntegerField(choices=yn, default=2)
    swql2 = models.IntegerField(choices=lang, default=4)
    swqnotes2 = models.TextField(null=True, blank=True)
    swqs3 = models.IntegerField(choices=yn, default=2)
    swqr3 = models.IntegerField(choices=yn, default=2)
    swql3 = models.IntegerField(choices=lang, default=4)
    swqnotes3 = models.TextField(null=True, blank=True)
    swqs4 = models.IntegerField(choices=yn, default=2)
    swqr4 = models.IntegerField(choices=yn, default=2)
    swql4 = models.IntegerField(choices=lang, default=4)
    swqnotes4 = models.TextField(null=True, blank=True)

    seqs1 = models.IntegerField(choices=yn, default=2)
    seqr1 = models.IntegerField(choices=yn, default=2)
    seql1 = models.IntegerField(choices=lang, default=4)
    seqnotes1 = models.TextField(null=True, blank=True)
    seqs2 = models.IntegerField(choices=yn, default=2)
    seqr2 = models.IntegerField(choices=yn, default=2)
    seql2 = models.IntegerField(choices=lang, default=4)
    seqnotes2 = models.TextField(null=True, blank=True)
    seqs3 = models.IntegerField(choices=yn, default=2)
    seqr3 = models.IntegerField(choices=yn, default=2)
    seql3 = models.IntegerField(choices=lang, default=4)
    seqnotes3 = models.TextField(null=True, blank=True)
    seqs4 = models.IntegerField(choices=yn, default=2)
    seqr4 = models.IntegerField(choices=yn, default=2)
    seql4 = models.IntegerField(choices=lang, default=4)
    seqnotes4 = models.TextField(null=True, blank=True)
    seqs5 = models.IntegerField(choices=yn, default=2)
    seqr5 = models.IntegerField(choices=yn, default=2)
    seql5 = models.IntegerField(choices=lang, default=4)
    seqnotes5 = models.TextField(null=True, blank=True)

    smqs1 = models.IntegerField(choices=yn, default=2)
    smqr1 = models.IntegerField(choices=yn, default=2)
    smql1 = models.IntegerField(choices=lang, default=4)
    smqnotes1 = models.TextField(null=True, blank=True)
    smqs2 = models.IntegerField(choices=yn, default=2)
    smqr2 = models.IntegerField(choices=yn, default=2)
    smql2 = models.IntegerField(choices=lang, default=4)
    smqnotes2 = models.TextField(null=True, blank=True)
    smqs3 = models.IntegerField(choices=yn, default=2)
    smqr3 = models.IntegerField(choices=yn, default=2)
    smql3 = models.IntegerField(choices=lang, default=4)
    smqnotes3 = models.TextField(null=True, blank=True)
    smqs4 = models.IntegerField(choices=yn, default=2)
    smqr4 = models.IntegerField(choices=yn, default=2)
    smql4 = models.IntegerField(choices=lang, default=4)
    smqnotes4 = models.TextField(null=True, blank=True)
    smqs5 = models.IntegerField(choices=yn, default=2)
    smqr5 = models.IntegerField(choices=yn, default=2)
    smql5 = models.IntegerField(choices=lang, default=4)
    smqnotes5 = models.TextField(null=True, blank=True)
    smqs6 = models.IntegerField(choices=yn, default=2)
    smqr6 = models.IntegerField(choices=yn, default=2)
    smql6 = models.IntegerField(choices=lang, default=4)
    smqnotes6 = models.TextField(null=True, blank=True)
    smqs7 = models.IntegerField(choices=yn, default=2)
    smqr7 = models.IntegerField(choices=yn, default=2)
    smql7 = models.IntegerField(choices=lang, default=4)
    smqnotes7 = models.TextField(null=True, blank=True)

    def __str__(self):
        return str(self.uid)

    def __getitem__(self, key):
        return getattr(self, key)
