from django.db import models
from django.contrib.auth.models import User


class String(models.Model):
    uid = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    lang = [(1, 'Python'), (2, 'C++'), (3, 'Java'), (4, 'Other')]
    yn = [(1, 'Yes'), (2, 'No')]

    eqs1 = models.IntegerField(choices=yn, default=2)
    eqr1 = models.IntegerField(choices=yn, default=2)
    eql1 = models.IntegerField(choices=lang, default=4)
    eqnotes1 = models.TextField(null=True, blank=True)
    eqs2 = models.IntegerField(choices=yn, default=2)
    eqr2 = models.IntegerField(choices=yn, default=2)
    eql2 = models.IntegerField(choices=lang, default=4)
    eqnotes2 = models.TextField(null=True, blank=True)
    eqs3 = models.IntegerField(choices=yn, default=2)
    eqr3 = models.IntegerField(choices=yn, default=2)
    eql3 = models.IntegerField(choices=lang, default=4)
    eqnotes3 = models.TextField(null=True, blank=True)
    eqs4 = models.IntegerField(choices=yn, default=2)
    eqr4 = models.IntegerField(choices=yn, default=2)
    eql4 = models.IntegerField(choices=lang, default=4)
    eqnotes4 = models.TextField(null=True, blank=True)
    eqs5 = models.IntegerField(choices=yn, default=2)
    eqr5 = models.IntegerField(choices=yn, default=2)
    eql5 = models.IntegerField(choices=lang, default=4)
    eqnotes5 = models.TextField(null=True, blank=True)

    mqs1 = models.IntegerField(choices=yn, default=2)
    mqr1 = models.IntegerField(choices=yn, default=2)
    mql1 = models.IntegerField(choices=lang, default=4)
    mqnotes1 = models.TextField(null=True, blank=True)
    mqs2 = models.IntegerField(choices=yn, default=2)
    mqr2 = models.IntegerField(choices=yn, default=2)
    mql2 = models.IntegerField(choices=lang, default=4)
    mqnotes2 = models.TextField(null=True, blank=True)
    mqs3 = models.IntegerField(choices=yn, default=2)
    mqr3 = models.IntegerField(choices=yn, default=2)
    mql3 = models.IntegerField(choices=lang, default=4)
    mqnotes3 = models.TextField(null=True, blank=True)
    mqs4 = models.IntegerField(choices=yn, default=2)
    mqr4 = models.IntegerField(choices=yn, default=2)
    mql4 = models.IntegerField(choices=lang, default=4)
    mqnotes4 = models.TextField(null=True, blank=True)
    mqs5 = models.IntegerField(choices=yn, default=2)
    mqr5 = models.IntegerField(choices=yn, default=2)
    mql5 = models.IntegerField(choices=lang, default=4)
    mqnotes5 = models.TextField(null=True, blank=True)
    mqs6 = models.IntegerField(choices=yn, default=2)
    mqr6 = models.IntegerField(choices=yn, default=2)
    mql6 = models.IntegerField(choices=lang, default=4)
    mqnotes6 = models.TextField(null=True, blank=True)
    mqs7 = models.IntegerField(choices=yn, default=2)
    mqr7 = models.IntegerField(choices=yn, default=2)
    mql7 = models.IntegerField(choices=lang, default=4)
    mqnotes7 = models.TextField(null=True, blank=True)
    mqs8 = models.IntegerField(choices=yn, default=2)
    mqr8 = models.IntegerField(choices=yn, default=2)
    mql8 = models.IntegerField(choices=lang, default=4)
    mqnotes8 = models.TextField(null=True, blank=True)
    mqs9 = models.IntegerField(choices=yn, default=2)
    mqr9 = models.IntegerField(choices=yn, default=2)
    mql9 = models.IntegerField(choices=lang, default=4)
    mqnotes9 = models.TextField(null=True, blank=True)
    mqs10 = models.IntegerField(choices=yn, default=2)
    mqr10 = models.IntegerField(choices=yn, default=2)
    mql10 = models.IntegerField(choices=lang, default=4)
    mqnotes10 = models.TextField(null=True, blank=True)

    hqs1 = models.IntegerField(choices=yn, default=2)
    hqr1 = models.IntegerField(choices=yn, default=2)
    hql1 = models.IntegerField(choices=lang, default=4)
    hqnotes1 = models.TextField(null=True, blank=True)
    hqs2 = models.IntegerField(choices=yn, default=2)
    hqr2 = models.IntegerField(choices=yn, default=2)
    hql2 = models.IntegerField(choices=lang, default=4)
    hqnotes2 = models.TextField(null=True, blank=True)
    hqs3 = models.IntegerField(choices=yn, default=2)
    hqr3 = models.IntegerField(choices=yn, default=2)
    hql3 = models.IntegerField(choices=lang, default=4)
    hqnotes3 = models.TextField(null=True, blank=True)
    hqs4 = models.IntegerField(choices=yn, default=2)
    hqr4 = models.IntegerField(choices=yn, default=2)
    hql4 = models.IntegerField(choices=lang, default=4)
    hqnotes4 = models.TextField(null=True, blank=True)
    hqs5 = models.IntegerField(choices=yn, default=2)
    hqr5 = models.IntegerField(choices=yn, default=2)
    hql5 = models.IntegerField(choices=lang, default=4)
    hqnotes5 = models.TextField(null=True, blank=True)
    hqs6 = models.IntegerField(choices=yn, default=2)
    hqr6 = models.IntegerField(choices=yn, default=2)
    hql6 = models.IntegerField(choices=lang, default=4)
    hqnotes6 = models.TextField(null=True, blank=True)
    hqs7 = models.IntegerField(choices=yn, default=2)
    hqr7 = models.IntegerField(choices=yn, default=2)
    hql7 = models.IntegerField(choices=lang, default=4)
    hqnotes7 = models.TextField(null=True, blank=True)

    def __str__(self):
        return str(self.uid)

    def __getitem__(self, key):
        return getattr(self, key)
