from django.db import models
from django.contrib.auth.models import User


# BFS and DFS
class Trav(models.Model):
    uid = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    lang = [(1, 'Python'), (2, 'C++'), (3, 'Java'), (4, 'Other')]
    yn = [(1, 'Yes'), (2, 'No')]

    bmqs1 = models.IntegerField(choices=yn, default=2)
    bmqr1 = models.IntegerField(choices=yn, default=2)
    bmql1 = models.IntegerField(choices=lang, default=4)
    bmqnotes1 = models.TextField(null=True, blank=True)
    bmqs2 = models.IntegerField(choices=yn, default=2)
    bmqr2 = models.IntegerField(choices=yn, default=2)
    bmql2 = models.IntegerField(choices=lang, default=4)
    bmqnotes2 = models.TextField(null=True, blank=True)
    bmqs3 = models.IntegerField(choices=yn, default=2)
    bmqr3 = models.IntegerField(choices=yn, default=2)
    bmql3 = models.IntegerField(choices=lang, default=4)
    bmqnotes3 = models.TextField(null=True, blank=True)
    bmqs4 = models.IntegerField(choices=yn, default=2)
    bmqr4 = models.IntegerField(choices=yn, default=2)
    bmql4 = models.IntegerField(choices=lang, default=4)
    bmqnotes4 = models.TextField(null=True, blank=True)
    bmqs5 = models.IntegerField(choices=yn, default=2)
    bmqr5 = models.IntegerField(choices=yn, default=2)
    bmql5 = models.IntegerField(choices=lang, default=4)
    bmqnotes5 = models.TextField(null=True, blank=True)

    bhqs1 = models.IntegerField(choices=yn, default=2)
    bhqr1 = models.IntegerField(choices=yn, default=2)
    bhql1 = models.IntegerField(choices=lang, default=4)
    bhqnotes1 = models.TextField(null=True, blank=True)
    bhqs2 = models.IntegerField(choices=yn, default=2)
    bhqr2 = models.IntegerField(choices=yn, default=2)
    bhql2 = models.IntegerField(choices=lang, default=4)
    bhqnotes2 = models.TextField(null=True, blank=True)
    bhqs3 = models.IntegerField(choices=yn, default=2)
    bhqr3 = models.IntegerField(choices=yn, default=2)
    bhql3 = models.IntegerField(choices=lang, default=4)
    bhqnotes3 = models.TextField(null=True, blank=True)
    bhqs4 = models.IntegerField(choices=yn, default=2)
    bhqr4 = models.IntegerField(choices=yn, default=2)
    bhql4 = models.IntegerField(choices=lang, default=4)
    bhqnotes4 = models.TextField(null=True, blank=True)

    dmqs1 = models.IntegerField(choices=yn, default=2)
    dmqr1 = models.IntegerField(choices=yn, default=2)
    dmql1 = models.IntegerField(choices=lang, default=4)
    dmqnotes1 = models.TextField(null=True, blank=True)
    dmqs2 = models.IntegerField(choices=yn, default=2)
    dmqr2 = models.IntegerField(choices=yn, default=2)
    dmql2 = models.IntegerField(choices=lang, default=4)
    dmqnotes2 = models.TextField(null=True, blank=True)
    dmqs3 = models.IntegerField(choices=yn, default=2)
    dmqr3 = models.IntegerField(choices=yn, default=2)
    dmql3 = models.IntegerField(choices=lang, default=4)
    dmqnotes3 = models.TextField(null=True, blank=True)
    dmqs4 = models.IntegerField(choices=yn, default=2)
    dmqr4 = models.IntegerField(choices=yn, default=2)
    dmql4 = models.IntegerField(choices=lang, default=4)
    dmqnotes4 = models.TextField(null=True, blank=True)
    dmqs5 = models.IntegerField(choices=yn, default=2)
    dmqr5 = models.IntegerField(choices=yn, default=2)
    dmql5 = models.IntegerField(choices=lang, default=4)
    dmqnotes5 = models.TextField(null=True, blank=True)
    dmqs6 = models.IntegerField(choices=yn, default=2)
    dmqr6 = models.IntegerField(choices=yn, default=2)
    dmql6 = models.IntegerField(choices=lang, default=4)
    dmqnotes6 = models.TextField(null=True, blank=True)
    dmqs7 = models.IntegerField(choices=yn, default=2)
    dmqr7 = models.IntegerField(choices=yn, default=2)
    dmql7 = models.IntegerField(choices=lang, default=4)
    dmqnotes7 = models.TextField(null=True, blank=True)
    dmqs8 = models.IntegerField(choices=yn, default=2)
    dmqr8 = models.IntegerField(choices=yn, default=2)
    dmql8 = models.IntegerField(choices=lang, default=4)
    dmqnotes8 = models.TextField(null=True, blank=True)
    dmqs9 = models.IntegerField(choices=yn, default=2)
    dmqr9 = models.IntegerField(choices=yn, default=2)
    dmql9 = models.IntegerField(choices=lang, default=4)
    dmqnotes9 = models.TextField(null=True, blank=True)

    dhqs1 = models.IntegerField(choices=yn, default=2)
    dhqr1 = models.IntegerField(choices=yn, default=2)
    dhql1 = models.IntegerField(choices=lang, default=4)
    dhqnotes1 = models.TextField(null=True, blank=True)
    dhqs2 = models.IntegerField(choices=yn, default=2)
    dhqr2 = models.IntegerField(choices=yn, default=2)
    dhql2 = models.IntegerField(choices=lang, default=4)
    dhqnotes2 = models.TextField(null=True, blank=True)
    dhqs3 = models.IntegerField(choices=yn, default=2)
    dhqr3 = models.IntegerField(choices=yn, default=2)
    dhql3 = models.IntegerField(choices=lang, default=4)
    dhqnotes3 = models.TextField(null=True, blank=True)
    dhqs4 = models.IntegerField(choices=yn, default=2)
    dhqr4 = models.IntegerField(choices=yn, default=2)
    dhql4 = models.IntegerField(choices=lang, default=4)
    dhqnotes4 = models.TextField(null=True, blank=True)
    dhqs5 = models.IntegerField(choices=yn, default=2)
    dhqr5 = models.IntegerField(choices=yn, default=2)
    dhql5 = models.IntegerField(choices=lang, default=4)
    dhqnotes5 = models.TextField(null=True, blank=True)
    dhqs6 = models.IntegerField(choices=yn, default=2)
    dhqr6 = models.IntegerField(choices=yn, default=2)
    dhql6 = models.IntegerField(choices=lang, default=4)
    dhqnotes6 = models.TextField(null=True, blank=True)
    dhqs7 = models.IntegerField(choices=yn, default=2)
    dhqr7 = models.IntegerField(choices=yn, default=2)
    dhql7 = models.IntegerField(choices=lang, default=4)
    dhqnotes7 = models.TextField(null=True, blank=True)
    dhqs8 = models.IntegerField(choices=yn, default=2)
    dhqr8 = models.IntegerField(choices=yn, default=2)
    dhql8 = models.IntegerField(choices=lang, default=4)
    dhqnotes8 = models.TextField(null=True, blank=True)

    def __str__(self):
        return str(self.uid)

    def __getitem__(self, key):
        return getattr(self, key)
